### PR TITLE
Provide RSSI as numeric

### PR DESCRIPTION
**Pull request by bschwehn**
All other values are numeric, so rssi should also be numeric to simplify handling of MQTT messages consistently.

### CODE REVIEW

**Comment by bschwehn** [comment]
I like that @cederlys  added the RSSI value, but in my opinion the value should be provided as numeric, not as string with unit. 

That is, this change will change the MQTT message from 

{"rssi": "-76 dbM"} to {"rssi":-76)

this is consistent with the temps/humidity which are also provided numerically and therefore allows consistent handling of all the sensor messages. 

Note: this may break setups for people that already rely on it being provided as a string!

**Comment by leon-anavi** [comment]
Thank you! Looks good to me and I have merged it.

Thanks,
Leon

**Comment by cederlys** [comment]
For the record, I think this is a good change. I have not yet done anything with the value (except looking at it manually) but I'm thinking about importing it (along with the other sensor values) to graphite.  I would probably ended up with the same conclusion.

Thanks for improving my improvement!

**Comment by bschwehn** [comment]
Right, makes for some pretty graphs and with a couple of them distributed around the apartment, it is actually somewhat useful when you want to evaluate options to improve WiFi connections at home :+1: 

2019-05-02-224832_3840x1080_scrot

**Pull request merged**
